local function fresh()
  package.loaded["ora.config"] = nil
  return require("ora.config")
end

describe("ora.config", function()
  describe("setup() — valid input", function()
    it("accepts minimal valid config (sqlcl_path only)", function()
      local c = fresh()
      assert.has_no_error(function()
        c.setup({ sqlcl_path = "sql" })
      end)
    end)

    it("sets sqlcl_path from user config", function()
      local c = fresh()
      c.setup({ sqlcl_path = "/opt/oracle/sqlcl/bin/sql" })
      assert.equals("/opt/oracle/sqlcl/bin/sql", c.values.sqlcl_path)
    end)

    it("applies default win_width and win_height", function()
      local c = fresh()
      c.setup({ sqlcl_path = "sql" })
      assert.equals(60, c.values.win_width)
      assert.equals(20, c.values.win_height)
    end)

    it("overrides win_width and win_height", function()
      local c = fresh()
      c.setup({ sqlcl_path = "sql", win_width = 80, win_height = 30 })
      assert.equals(80, c.values.win_width)
      assert.equals(30, c.values.win_height)
    end)

    it("overwrites values on a second setup() call", function()
      local c = fresh()
      c.setup({ sqlcl_path = "sql",  win_width = 60 })
      c.setup({ sqlcl_path = "sql2", win_width = 90 })
      assert.equals("sql2", c.values.sqlcl_path)
      assert.equals(90,     c.values.win_width)
    end)

    it("does not bleed between module reloads", function()
      local c1 = fresh()
      c1.setup({ sqlcl_path = "sql1" })
      local c2 = fresh()
      assert.equals("sql", c2.values.sqlcl_path)  -- back to default
    end)

    it("treats nil sqlcl_path as absent (keeps default 'sql')", function()
      local c = fresh()
      assert.has_no_error(function() c.setup({ sqlcl_path = nil }) end)
      assert.equals("sql", c.values.sqlcl_path)
    end)
  end)

  describe("setup() — sqlcl_path validation", function()
    it("errors when sqlcl_path is an empty string", function()
      local c = fresh()
      local ok, err = pcall(c.setup, { sqlcl_path = "" })
      assert.is_false(ok)
      assert.matches("sqlcl_path", err)
    end)

    it("errors when sqlcl_path is a number", function()
      local c = fresh()
      local ok, err = pcall(c.setup, { sqlcl_path = 42 })
      assert.is_false(ok)
      assert.matches("sqlcl_path", err)
    end)

    it("errors when sqlcl_path is a table", function()
      local c = fresh()
      local ok, err = pcall(c.setup, { sqlcl_path = {} })
      assert.is_false(ok)
      assert.matches("sqlcl_path", err)
    end)
  end)
end)
